perceptive_target_trajectories_publisher:
  ros__parameters:
    robot_name: legged_robot
    referenceFile: /workspace/install/legged_controllers/share/legged_controllers/config/p1/reference.info
    taskFile: /workspace/src/perceptive_legged_control/perceptive_legged_control/config/p1/task.info
    terrain_topic: /convex_plane_decomposition_ros/planar_terrain
    terrain_height_layer: smooth_planar
    fallback_height_layer: elevation
    terrain_height_offset: 0.0
    command_horizon_scale: 1.0
